using Laura.Core.Conversation;

namespace Laura.Core.Abstractions;

/// <summary>
/// Extension point for answers generated by a language model.
///
/// It is deliberately optional: the dispatcher only queries it after all
/// skills reject the command, and the default implementation does nothing. This way
/// Laura permanece inteiramente funcional e offline, e conectar um provedor local
/// adding something like Ollama later only means registering another implementation of this interface.
/// </summary>
public interface IConversationEngine
{
    /// <summary>
    /// Gets a value indicating whether the engine is configured and ready to answer.
    /// </summary>
    bool IsAvailable { get; }

    /// <summary>
    /// Pede uma answer ao modelo.
    ///
    /// Args:
    ///     turn: Prompt and user context.
    ///     cancellationToken: Token that aborts the request.
    ///
    /// Returns:
    ///     The answer to speak, or <see langword="null"/> when the engine is not
    ///     available or could not answer. Provider failures must not
    ///     propagate exceptions: Laura must fall back to the default answer.
    /// </summary>
    Task<string?> AskAsync(ConversationTurn turn, CancellationToken cancellationToken = default);
}
